In [1]:
#0-D array
import numpy as np
arr = np.array([22])   #array function use to create any type of array
print(arr)

[22]


In [6]:
#1-D Array
arr=np.array([11,12,13,14,15])
print(arr)
print(arr[3])
print(arr[1]+arr[3])

[11 12 13 14 15]
14
26


In [17]:
#2-D Array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))    #it will return type of the array object
print(arr[0,1])
print(arr[1,1])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
5


In [2]:
#3-D Array
arr = np.array([[[11,12,13],[10,20,30],[21,22,23]]])
print(arr)

[[[11 12 13]
  [10 20 30]
  [21 22 23]]]


In [5]:
#array slicing
ar=np.array([12,6,7,8,3,4])
print(ar[1:4])
print(ar[:4])

[6 7 8]
[12  6  7  8]


In [7]:
#joining or concatenating arrays(1-D Arrays)
a1=np.array([10,20,30])
a2=np.array([40,50,60])
result = np.concatenate([a1,a2])
print(result)

[10 20 30 40 50 60]


In [9]:
#joining 2-D Arrays
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate([arr1,arr2],axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [10]:
arr=np.array([10,20,30,40,10,50,60,10])
x=np.where(arr==10)
print(x)

(array([0, 4, 7], dtype=int64),)


In [11]:
#sorting an array
arr=np.array([12,5,25,6,28,30,3])
a=np.sort(arr)
print(a)

[ 3  5  6 12 25 28 30]
